// <auto-generated />
using DataAcessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommece.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607112211_Intial")]
    partial class Intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAcessLayer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Novels"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Science"
                        });
                });

            modelBuilder.Entity("E_commerce.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListPrice")
                        .HasColumnType("int");

                    b.Property<int>("PriceFor100Plus")
                        .HasColumnType("int");

                    b.Property<int>("PriceFor1To50")
                        .HasColumnType("int");

                    b.Property<int>("PriceFor50Plus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A Handbook of Agile Software Craftsmanship",
                            ISBN = "9780132350884",
                            ImageUrl = "",
                            ListPrice = 500,
                            PriceFor100Plus = 400,
                            PriceFor1To50 = 450,
                            PriceFor50Plus = 420,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Your Journey to Mastery",
                            ISBN = "9780201616224",
                            ImageUrl = "",
                            ListPrice = 550,
                            PriceFor100Plus = 450,
                            PriceFor1To50 = 500,
                            PriceFor50Plus = 470,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Elements of Reusable Object-Oriented Software",
                            ISBN = "9780201633610",
                            ImageUrl = "",
                            ListPrice = 600,
                            PriceFor100Plus = 500,
                            PriceFor1To50 = 550,
                            PriceFor50Plus = 520,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Fantasy novel series",
                            ISBN = "9780747532743",
                            ImageUrl = "",
                            ListPrice = 300,
                            PriceFor100Plus = 230,
                            PriceFor1To50 = 270,
                            PriceFor50Plus = 250,
                            Title = "Harry Potter"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Fantasy adventure novel",
                            ISBN = "9780261103344",
                            ImageUrl = "",
                            ListPrice = 320,
                            PriceFor100Plus = 250,
                            PriceFor1To50 = 290,
                            PriceFor50Plus = 270,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Dystopian novel",
                            ISBN = "9780451524935",
                            ImageUrl = "",
                            ListPrice = 280,
                            PriceFor100Plus = 210,
                            PriceFor1To50 = 250,
                            PriceFor50Plus = 230,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Cosmology explained",
                            ISBN = "9780553380163",
                            ImageUrl = "",
                            ListPrice = 400,
                            PriceFor100Plus = 330,
                            PriceFor1To50 = 370,
                            PriceFor50Plus = 350,
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Evolutionary biology book",
                            ISBN = "9780199291151",
                            ImageUrl = "",
                            ListPrice = 420,
                            PriceFor100Plus = 350,
                            PriceFor1To50 = 390,
                            PriceFor50Plus = 370,
                            Title = "The Selfish Gene"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Science and universe exploration",
                            ISBN = "9780345539434",
                            ImageUrl = "",
                            ListPrice = 450,
                            PriceFor100Plus = 380,
                            PriceFor1To50 = 420,
                            PriceFor50Plus = 400,
                            Title = "Cosmos"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Rules for focused success",
                            ISBN = "9781455586691",
                            ImageUrl = "",
                            ListPrice = 380,
                            PriceFor100Plus = 310,
                            PriceFor1To50 = 350,
                            PriceFor50Plus = 330,
                            Title = "Deep Work"
                        });
                });

            modelBuilder.Entity("E_commerce.DAL.Entities.Product", b =>
                {
                    b.HasOne("DataAcessLayer.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAcessLayer.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
