// <auto-generated />
using DataAcessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_commerce.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAcessLayer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Database"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Artificial Intelligence"
                        });
                });

            modelBuilder.Entity("E_commerce.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListPrice")
                        .HasColumnType("int");

                    b.Property<int>("PriceFor100Plus")
                        .HasColumnType("int");

                    b.Property<int>("PriceFor1To50")
                        .HasColumnType("int");

                    b.Property<int>("PriceFor50Plus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert Martin",
                            CategoryId = 4,
                            Description = "A handbook of agile software craftsmanship.",
                            ISBN = "9780132350884",
                            ImageUrl = "",
                            ListPrice = 60,
                            PriceFor100Plus = 45,
                            PriceFor1To50 = 55,
                            PriceFor50Plus = 50,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrew Hunt",
                            CategoryId = 4,
                            Description = "Classic guide for software developers.",
                            ISBN = "9780135957059",
                            ImageUrl = "",
                            ListPrice = 65,
                            PriceFor100Plus = 50,
                            PriceFor1To50 = 60,
                            PriceFor50Plus = 55,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Erich Gamma",
                            CategoryId = 4,
                            Description = "Elements of reusable object oriented software.",
                            ISBN = "9780201633610",
                            ImageUrl = "",
                            ListPrice = 70,
                            PriceFor100Plus = 55,
                            PriceFor1To50 = 65,
                            PriceFor50Plus = 60,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jon Skeet",
                            CategoryId = 1,
                            Description = "Deep dive into advanced C# concepts.",
                            ISBN = "9781617294532",
                            ImageUrl = "",
                            ListPrice = 55,
                            PriceFor100Plus = 40,
                            PriceFor1To50 = 50,
                            PriceFor50Plus = 45,
                            Title = "C# in Depth"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Adam Freeman",
                            CategoryId = 3,
                            Description = "Comprehensive guide to ASP.NET Core.",
                            ISBN = "9781484269237",
                            ImageUrl = "",
                            ListPrice = 75,
                            PriceFor100Plus = 60,
                            PriceFor1To50 = 70,
                            PriceFor50Plus = 65,
                            Title = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Itzik BenGan",
                            CategoryId = 2,
                            Description = "Practical T SQL fundamentals and techniques.",
                            ISBN = "9781509302000",
                            ImageUrl = "",
                            ListPrice = 50,
                            PriceFor100Plus = 35,
                            PriceFor1To50 = 45,
                            PriceFor50Plus = 40,
                            Title = "SQL Server"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Eric Matthes",
                            CategoryId = 1,
                            Description = "Fast paced introduction to Python.",
                            ISBN = "9781718502703",
                            ImageUrl = "",
                            ListPrice = 45,
                            PriceFor100Plus = 30,
                            PriceFor1To50 = 40,
                            PriceFor50Plus = 35,
                            Title = "Python Crash"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Ian Goodfellow",
                            CategoryId = 5,
                            Description = "Foundational deep learning concepts.",
                            ISBN = "9780262035613",
                            ImageUrl = "",
                            ListPrice = 80,
                            PriceFor100Plus = 65,
                            PriceFor1To50 = 75,
                            PriceFor50Plus = 70,
                            Title = "Deep Learning"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Aurelien Geron",
                            CategoryId = 5,
                            Description = "Machine learning with Scikit Learn and TensorFlow.",
                            ISBN = "9781098125974",
                            ImageUrl = "",
                            ListPrice = 85,
                            PriceFor100Plus = 70,
                            PriceFor1To50 = 80,
                            PriceFor50Plus = 75,
                            Title = "Hands On ML"
                        },
                        new
                        {
                            Id = 10,
                            Author = "David Flanagan",
                            CategoryId = 3,
                            Description = "Definitive JavaScript reference and guide.",
                            ISBN = "9781491952023",
                            ImageUrl = "",
                            ListPrice = 60,
                            PriceFor100Plus = 45,
                            PriceFor1To50 = 55,
                            PriceFor50Plus = 50,
                            Title = "JavaScript Guide"
                        });
                });

            modelBuilder.Entity("E_commerce.DAL.Entities.Product", b =>
                {
                    b.HasOne("DataAcessLayer.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAcessLayer.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
